-- Phase 3 domain schema (docs/design/initial-build-scope.md, crossing
-- docs/FUNCTIONAL_SPEC.md §4 with the Plaid pipeline design).
--
-- Numeric policy (§2): money and fractions are NUMERIC(20,4),
-- quantities and FX rates NUMERIC(20,8) — exact decimals, never floats.
-- Currency is a property of the account (§5); a security's currency
-- must match every account that holds it (enforced at write time in
-- code — cross-table checks don't fit a CHECK constraint).
--
-- Foreign keys default to NO ACTION so the §5.9 guard rails (delete
-- only when unreferenced) are backed by the database.
--
-- Plaid snapshot staging and linkage tables are deliberately absent:
-- they mirror bankferry's snapshot proto, whose field-level contract is
-- not yet final, and land with the importer.

-- Identity: many users / many portfolios with a grant join was designed
-- into legacy and stays in the schema (FUNCTIONAL_SPEC §3.2); the app
-- auto-creates one portfolio per user on first authenticated request.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE portfolios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE portfolio_grants (
    user_id BIGINT NOT NULL REFERENCES users(id),
    portfolio_id BIGINT NOT NULL REFERENCES portfolios(id),
    PRIMARY KEY (user_id, portfolio_id)
);

CREATE TABLE brokers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL REFERENCES portfolios(id),
    name VARCHAR(255) NOT NULL,
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (portfolio_id, name)
);

-- Sweep balance carries provenance: maintained by hand or updated from
-- an imported snapshot's cash-equivalent holdings (§1).
CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    broker_id BIGINT NOT NULL REFERENCES brokers(id),
    name VARCHAR(255) NOT NULL,
    account_number VARCHAR(64) NOT NULL,
    currency CHAR(3) NOT NULL,
    tax_deferred BOOLEAN NOT NULL DEFAULT FALSE,
    sweep_balance NUMERIC(20,4) NOT NULL DEFAULT 0,
    sweep_source VARCHAR(16) NOT NULL DEFAULT 'manual',
    sweep_as_of DATE,
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (broker_id, name)
);

-- pricing_locus: 'MARKET' (external provider prices it) or 'MANUAL'
-- (hand-entered private_prices rows); a VARCHAR rather than a boolean
-- so later venue/exchange nuance is additive (§4).
CREATE TABLE securities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL REFERENCES portfolios(id),
    ticker VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL DEFAULT '',
    currency CHAR(3) NOT NULL,
    pricing_locus VARCHAR(16) NOT NULL DEFAULT 'MANUAL',
    net_expense_ratio NUMERIC(20,4),
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (portfolio_id, ticker)
);

-- Asset classes are seed data, not a closed enum (§4/§6): adding e.g.
-- 'Commodities' later is an INSERT, not schema surgery.
CREATE TABLE asset_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    display_order INT NOT NULL
);

INSERT INTO asset_classes (name, display_order) VALUES
    ('Cash', 1),
    ('US Stock', 2),
    ('Non US Stock', 3),
    ('Bond', 4),
    ('Other', 5);

-- Generic classification storage (§4): kind 'ASSET_CLASS' at launch
-- (class_key = asset_classes.name); deferred taxonomies (sector,
-- market cap, region, credit quality) revive as new kinds. as_of
-- date-stamps the mix so staleness can prompt a refresh; all rows of
-- one (security, kind) are written atomically with the same as_of.
CREATE TABLE security_classifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL REFERENCES securities(id),
    kind VARCHAR(32) NOT NULL,
    class_key VARCHAR(64) NOT NULL,
    weight NUMERIC(20,4) NOT NULL,
    as_of DATE NOT NULL,
    UNIQUE (security_id, kind, class_key)
);

CREATE TABLE target_allocations (
    portfolio_id BIGINT NOT NULL REFERENCES portfolios(id),
    asset_class_id BIGINT NOT NULL REFERENCES asset_classes(id),
    fraction NUMERIC(20,4) NOT NULL,
    PRIMARY KEY (portfolio_id, asset_class_id)
);

-- Position-level holdings: the system of record for tax-deferred
-- accounts (no lots, no basis — §1), updated by hand or by snapshot
-- import with provenance. Taxable accounts derive positions from
-- purchase_lots instead and have no rows here.
CREATE TABLE holdings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    security_id BIGINT NOT NULL REFERENCES securities(id),
    quantity NUMERIC(20,8) NOT NULL,
    source VARCHAR(16) NOT NULL DEFAULT 'manual',
    as_of DATE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (account_id, security_id)
);

-- The tax record for taxable accounts (§1). Native DECIMAL and DATE
-- columns — the legacy formatted-string storage is a fix-don't-port
-- defect (FUNCTIONAL_SPEC §4.3).
CREATE TABLE purchase_lots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    security_id BIGINT NOT NULL REFERENCES securities(id),
    date_bought DATE NOT NULL,
    quantity NUMERIC(20,8) NOT NULL,
    price_per_share NUMERIC(20,4) NOT NULL,
    purchase_costs NUMERIC(20,4) NOT NULL DEFAULT 0
);

CREATE INDEX idx_purchase_lots_position ON purchase_lots (account_id, security_id);

-- One sale, allocated across lots. Per-lot sale-cost apportionment is
-- derived (Money.allocateBy over shares_sold — deterministic), never
-- stored, so editing an allocation cannot desynchronize stored costs.
CREATE TABLE sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    security_id BIGINT NOT NULL REFERENCES securities(id),
    sale_date DATE NOT NULL,
    price_per_share NUMERIC(20,4) NOT NULL,
    sale_costs NUMERIC(20,4) NOT NULL DEFAULT 0
);

CREATE INDEX idx_sales_date ON sales (sale_date);

CREATE TABLE sale_allocations (
    sale_id BIGINT NOT NULL REFERENCES sales(id),
    lot_id BIGINT NOT NULL REFERENCES purchase_lots(id),
    shares_sold NUMERIC(20,8) NOT NULL,
    PRIMARY KEY (sale_id, lot_id)
);

-- Hand-entered price history for MANUAL-locus securities (trust
-- instruments, the Euro investment, gold bullion — §6); price_date is
-- the as-of date, source records who/what entered it.
CREATE TABLE private_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL REFERENCES securities(id),
    price_date DATE NOT NULL,
    price NUMERIC(20,4) NOT NULL,
    source VARCHAR(16) NOT NULL DEFAULT 'manual',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (security_id, price_date)
);

-- Dated FX rates (§5): the only path between currencies. rate is
-- quote-per-base (e.g. base EUR, quote USD, rate 1.09).
CREATE TABLE fx_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_currency CHAR(3) NOT NULL,
    quote_currency CHAR(3) NOT NULL,
    rate_date DATE NOT NULL,
    rate NUMERIC(20,8) NOT NULL,
    source VARCHAR(32) NOT NULL,
    UNIQUE (base_currency, quote_currency, rate_date)
);
