-- Daily bars for MARKET-locus securities, fetched from the Decision 4
-- providers (Tiingo primary, EODHD fallback). This table is also the
-- spec §6.1 restart-surviving cache: fetched_at drives the multi-hour
-- freshness TTL. Provider data lives here and only here — never in
-- the repository (Decision 4 persistence boundary).
CREATE TABLE market_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL REFERENCES securities(id),
    price_date DATE NOT NULL,
    open NUMERIC(20,4) NOT NULL,
    high NUMERIC(20,4) NOT NULL,
    low NUMERIC(20,4) NOT NULL,
    close NUMERIC(20,4) NOT NULL,
    adjusted_close NUMERIC(20,4) NOT NULL,
    -- Zero / one when the provider omits corporate actions (EODHD's
    -- bar endpoint does; its adjusted_close already reflects them).
    dividend NUMERIC(20,4) NOT NULL DEFAULT 0,
    split_coefficient NUMERIC(20,8) NOT NULL DEFAULT 1,
    volume BIGINT NOT NULL DEFAULT 0,
    source VARCHAR(16) NOT NULL,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (security_id, price_date)
);

CREATE INDEX idx_market_prices_security_date ON market_prices (security_id, price_date);
