-- Mark-to-market (PFIC §1296) tax treatment (build-scope §11).
--
-- tax_treatment is an open VARCHAR like the other securities enums:
-- server code parses it loudly; a future value is an additive
-- migration, not schema surgery.

ALTER TABLE securities ADD COLUMN tax_treatment VARCHAR(16) NOT NULL DEFAULT 'LOTS';

-- One row per elected security per tax year: the year-end mark that
-- was (or will be) filed. All USD amounts carry scale 4; quantity
-- scale 8; the FX rate is stored as filed (USD per one unit of the
-- security's currency).
CREATE TABLE mtm_marks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL REFERENCES securities(id),
    tax_year INT NOT NULL,
    mark_date DATE NOT NULL,
    quantity NUMERIC(30,8) NOT NULL,
    fmv_local NUMERIC(20,4) NOT NULL,
    fx_rate NUMERIC(20,8) NOT NULL,
    fmv_usd NUMERIC(20,4) NOT NULL,
    basis_before_usd NUMERIC(20,4) NOT NULL,
    basis_after_usd NUMERIC(20,4) NOT NULL,
    ordinary_income_usd NUMERIC(20,4) NOT NULL,
    UNIQUE (security_id, tax_year)
);
