-- bankferry snapshot uploads and Plaid account links (pipeline design
-- amended 2026-08-20: browser upload replaces the file drop).
--
-- Snapshots archive verbatim: the raw proto bytes stay in content so a
-- fixed processor can re-run against exactly what was uploaded. Status
-- is an open VARCHAR like the other enums; the last processing report
-- (serialized ImportReport proto) rides alongside.
CREATE TABLE snapshot_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL REFERENCES portfolios(id),
    filename VARCHAR(255) NOT NULL,
    content BLOB NOT NULL,
    schema_version INT NOT NULL,
    as_of DATE NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(16) NOT NULL DEFAULT 'UPLOADED',
    processed_at TIMESTAMP WITH TIME ZONE,
    report BLOB
);

-- One link per Plaid account_ref, chosen by the human in the import
-- screen; links persist across snapshots.
CREATE TABLE plaid_account_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_ref VARCHAR(128) NOT NULL UNIQUE,
    account_id BIGINT NOT NULL REFERENCES accounts(id)
);
