-- Trading plans (docs/design/trading-plan.md): a human-composed,
-- ordered list of buys, sells, transfers, and external adds/draws,
-- saved and printable. Plans are projections only - nothing here is a
-- trade; the real purchases, sales, holdings, and sweeps are recorded
-- afterwards through their own flows. Plans stay editable for their
-- whole life (ruling 2026-08-22); printing stamps last_printed_at and
-- nothing else.
CREATE TABLE trading_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL REFERENCES portfolios(id),
    name VARCHAR(120) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_printed_at TIMESTAMP WITH TIME ZONE
);

-- One row per step, in plan order. Amounts are in the step account's
-- currency; shares and amount are the human's entry (exactly one for
-- a trade), the other is derived at scoring time and never stored.
CREATE TABLE trading_plan_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL REFERENCES trading_plans(id) ON DELETE CASCADE,
    position INT NOT NULL,
    kind VARCHAR(16) NOT NULL,
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    to_account_id BIGINT REFERENCES accounts(id),
    security_id BIGINT REFERENCES securities(id),
    shares NUMERIC(20,4),
    amount NUMERIC(20,4),
    note VARCHAR(255) NOT NULL DEFAULT '',
    UNIQUE (plan_id, position)
);
